name: Collect Bootloader CVEs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Pull External Repositories
        run: |
          git submodule update --init --recursive

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Script
        run: |
          python3 generate_table.py
          cat description.md table.md > README.md

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Automated update: $(date)" || echo "No changes to commit"
          git push origin test
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
